/*
 * Discription:Program to implement hashing
 * Author:Nooras Fatima-16co01
 * Created on:Oct 5,2017
*/
#include<stdio.h>
#include<math.h>
#define MAX_SIZE 5
int hash(int n)
{
	return n%MAX_SIZE;
}

int linear_probe(int h)
{
	return ++h%MAX_SIZE;
}

int quadratic_probe(int h,int i)
{
	return (int)(h+pow(i,2))%MAX_SIZE;
}

int double_hash(int h,int i)
{
	return (h+i*linear_probe(h))%MAX_SIZE;
}

void display(int a[])
{
	int i;
	printf("\nTHE ELEMENT OF ARRAY ARE...\n");
	for(i=0;i<MAX_SIZE;i++)
		printf("%d\t",a[i]);
}
int main()
{
	int a[MAX_SIZE],i,h,e,count,choice;
	for(i=0;i<MAX_SIZE;i++)
		a[i]=-1;
	do
	{
		count=0;
		printf("\nENTER THE ELEMENT TO BE STORE:");
		scanf("%d",&e);
		h=hash(e);
		if(a[h]==-1)
		{	
			a[h]=e;
			display(a);
		}
		else
		{
			while(count<MAX_SIZE)
			{
				count++;
				printf("\nCOLLISION OCCURED AT %d",h);
				printf("\nPLEASE ENTER YOUR CHOICE FOR RESOLUTION:");
				printf("\n1.LINEAR PROBING\n2.QUADRATIC PROBING\n3.DOUBLE HASHING\n");
				scanf("%d",&choice);
				switch(choice)
				{
					case 1:
					h=linear_probe(h);
						break;
					case 2:
						h=quadratic_probe(h,count);
						break;
					case 3:
						h=double_hash(h,count);
						break;
					default:
						printf("INVALID CHOICE!!");
						count--;
						break;
				}
				
				if(a[h]==-1)
				{	
					a[h]=e;
					display(a);
					break;
				}
			}
		}
		if(count==MAX_SIZE)
		{
			printf("\nARRAY IS FULL OR RESOLUTION NOT SUCCESSFULL!!\n");
			return 0;
		}
	}while(1);
}

/*
OUTPUTS:
-------------------------------------------------
LINEAR PROBE:
-------------------------------------------------
ENTER THE ELEMENT TO BE STORE:4

THE ELEMENT OF ARRAY ARE...
-1	-1	-1	-1	4	
ENTER THE ELEMENT TO BE STORE:8

THE ELEMENT OF ARRAY ARE...
-1	-1	-1	8	4	
ENTER THE ELEMENT TO BE STORE:1

THE ELEMENT OF ARRAY ARE...
-1	1	-1	8	4	
ENTER THE ELEMENT TO BE STORE:7

THE ELEMENT OF ARRAY ARE...
-1	1	7	8	4	
ENTER THE ELEMENT TO BE STORE:3

COLLISION OCCURED AT 3
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

THE ELEMENT OF ARRAY ARE...
3	1	7	8	4	
ENTER THE ELEMENT TO BE STORE:2

COLLISION OCCURED AT 2
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

COLLISION OCCURED AT 3
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

COLLISION OCCURED AT 0
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

COLLISION OCCURED AT 1
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
1

ARRAY IS FULL OR RESOLUTION NOT SUCCESSFULL!!


------------------
(program exited with code: 0)
Press return to continue
-------------------------------------------------
QUADRATIC PROBE:
-------------------------------------------------
ENTER THE ELEMENT TO BE STORE:2

THE ELEMENT OF ARRAY ARE...
-1	-1	2	-1	-1	
ENTER THE ELEMENT TO BE STORE:6

THE ELEMENT OF ARRAY ARE...
-1	6	2	-1	-1	
ENTER THE ELEMENT TO BE STORE:9

THE ELEMENT OF ARRAY ARE...
-1	6	2	-1	9	
ENTER THE ELEMENT TO BE STORE:4

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

THE ELEMENT OF ARRAY ARE...
4	6	2	-1	9	
ENTER THE ELEMENT TO BE STORE:3

THE ELEMENT OF ARRAY ARE...
4	6	2	3	9	
ENTER THE ELEMENT TO BE STORE:2

COLLISION OCCURED AT 2
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

COLLISION OCCURED AT 3
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

COLLISION OCCURED AT 2
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

COLLISION OCCURED AT 1
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

COLLISION OCCURED AT 2
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
2

ARRAY IS FULL OR RESOLUTION NOT SUCCESSFULL!!


------------------
(program exited with code: 0)
Press return to continue
-------------------------------------------------
DOUBLE HASHING:
-------------------------------------------------
ENTER THE ELEMENT TO BE STORE:2

THE ELEMENT OF ARRAY ARE...
-1	-1	2	-1	-1	
ENTER THE ELEMENT TO BE STORE:3

THE ELEMENT OF ARRAY ARE...
-1	-1	2	3	-1	
ENTER THE ELEMENT TO BE STORE:4

THE ELEMENT OF ARRAY ARE...
-1	-1	2	3	4	
ENTER THE ELEMENT TO BE STORE:9

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
3

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
3

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
3

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
3

COLLISION OCCURED AT 4
PLEASE ENTER YOUR CHOICE FOR RESOLUTION:
1.LINEAR PROBING
2.QUADRATIC PROBING
3.DOUBLE HASHING
3

ARRAY IS FULL OR RESOLUTION NOT SUCCESSFULL!!


------------------
(program exited with code: 0)
Press return to continue

-------------------------------------------------
*/
